(function ensightenInit(){var ensightenOptions = {client: "tronc", clientId: 2115, publishPath: "nydailynewsarcprod", isPublic:0, serverComponentLocation: "eb.trbas.com/tronc/nydailynewsarcprod/serverComponent.php", staticJavascriptPath: "eb.trbas.com/tronc/nydailynewsarcprod/code/", ns: 'Bootstrapper', nexus:"eb.trbas.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Mon Aug 12 16:27:51 GMT 2019", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function n(){for(var a=b.dataDefinitionIds.length,c=!0,d=0;d<a;d++){var e=b.dataDefinitions[b.dataDefinitionIds[d]];if(!e||
null==e.endRegistration){c=!1;break}}c&&b.callOnDataDefintionComplete()}var e={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};e.version="1.26.0";e.nexus=f.nexus||"nexus.ensighten.com";e.rand=-1;e.currSec=(new Date).getSeconds();e.options={interval:f.interval||100,erLoc:f.errorLocation||e.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||e.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||e.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||e.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};e.ruleList=[];e.allDeploymentIds=[];e.runDeploymentIds=[];e.runRuleIds=[];e.exceptionList=[];e.ensightenVariables={};e.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var c=0;c<a.dependencies.length;c++)if(!1===a.dependencies[c]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;e.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;e.BeaconException=m;e.checkForInvalidDependencies=function(a,c,d,h){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new e.DependencyNotAvailableException(h[a])),c&&-1!==c&&e.allDeploymentIds.push(c),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var c=(e.currSec||0)%20,b=e.options.beaconSamplingSeedValue;-1===b?a=!0:0!==c&&0===b%c&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+e.options.scLoc,!1,a||!0,e.options.scUseCacheBuster)};b.setVariable=function(a,c){e.ensightenVariables[a]=
c};b.getVariable=function(a){return a in e.ensightenVariables?e.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<e.ruleList.length;a++)e.test(e.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();e.exceptionList.push(a);a=window.location.protocol+"//"+e.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(e.options.clientId||-1)+"&client="+encodeURIComponent(e.options.client||"")+"&publishPath="+encodeURIComponent(e.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(c){window[ensightenOptions.ns].reportException(c)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(e.runDeploymentIds.push(this.deploymentId),e.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;e.ruleList.push(a);
-1!==a.deploymentId&&e.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var c=0;c<e.ruleList.length;c++)if(e.ruleList[c].id===a)return e.ruleList[c];return!1};b.getRuleList=function(){return e.ruleList};b.clearRuleList=function(){e.ruleList=[]};b.getAllDeploymentIds=function(){return e.allDeploymentIds};b.getRunRuleIds=function(){return e.runRuleIds};b.getRunDeploymentIds=function(){return e.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};e.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var c=new Date;c=c.getFullYear()+"-"+e.toTwoChar(c.getMonth())+"-"+e.toTwoChar(c.getDate())+" "+e.toTwoChar(c.getHours())+":"+e.toTwoChar(c.getMinutes())+":"+e.toTwoChar(c.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(c);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+e.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+e.options.clientId+"&client="+e.options.client+"&publishPath="+e.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var c=new Image(0,0);c.src=a;return c};b.insertScript=function(a,c,d,h){var p=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==c?c:1)for(g=0;g<p.length;g++)if(p[g].src===a&&p[g].readyState&&/loaded|complete/.test(p[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;e.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));c=window.location.href;"object"===typeof d&&d.PageID&&(c=d.PageID,delete d.PageID);if("object"===typeof d)for(g in d){g=~c.indexOf("#")?c.slice(c.indexOf("#"),c.length):"";c=c.slice(0,g.length?c.length-g.length:
c.length);c+=~c.indexOf("?")?"&":"?";for(k in d)c+=k+"="+d[k]+"&";c=c.slice(0,-1)+g;break}a+="?";h&&(a+="r="+e.rand+"&");a+="ClientID="+encodeURIComponent(e.options.clientId)+"&PageID="+encodeURIComponent(c)}(function(a,c,b){var d=c.head||c.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=c.createElement("script");a.src=b;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,
d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,c,b){var d=document.getElementsByTagName("script"),e;b=d[0];for(e=0;e<d.length;e++)if(d[e].src===a&&d[e].readyState&&/loaded|complete/.test(d[e].readyState))try{c()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{c.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};b.parentNode.insertBefore(d,b)};b.insertPageFiles=function(a){var b=0,d=0,e=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();d++};for(b=0;b<a.length;++b)window[ensightenOptions.ns].loadScriptCallback(a[b],e)};b.unobtrusiveAddEvent=function(a,
b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(p){window[ensightenOptions.ns].reportException(p)}};b.anonymous=function(a,c){return function(){try{b.currentRuleId=c?c:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,
deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var c,d=0;d<a.length;++d)if(c=b.getRule(parseInt(a[d],10)),!c||!c.executionData.hasRun)return!1;return!0};
b.bindDependencyImmediate=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});
if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,
c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,c,d,f,p){var g=[];if(!e.checkForInvalidDependencies(c,f,d,p)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var c=a?a.length:0,d=0;d<c;d++){var e=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(e)&&b.dataDefinitionIds.push(e);else{for(var f=!1,g=
b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===e){f=!0;break}f||b.dataDefinitionIds.push(e)}}b.pageSpecificDataDefinitionsSet=!0;n()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,c){var d=b.dataDefinitions[c];d||(d=new b.DataDefinition(c,
a),b.dataDefinitions[c]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&n()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=
!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=
function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=
c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var e=0;e<c.length;e++)try{c[e].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=function(){return r()};e.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=
a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?e.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(e.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,
!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(b.executionState.DOMParsed=!0,b.executionState.DOMLoaded=!0);"true"===e.options.enableTagAuditBeacon&&b.sampleBeacon()&&
window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],c,d,h,l,g=0;g<e.ruleList.length;++g)d=e.ruleList[g],h=d.executionData.hasRun?"1":"0",l=d.deploymentId.toString()+"|"+d.id.toString()+"|"+h,a.push(l);c="["+a.join(";")+"]";var m=window.location.protocol+"//"+e.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+c+"&idx=0&r="+e.rand;b.imageRequest(m)}catch(q){b.currentRuleId=
-1,b.currentDeploymentId=-1,a=new e.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,e.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){f=f.timing||{};var l=f.navigationStart||0,m={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var n="&ns="+encodeURIComponent(f.navigationStart);for(var e in m)if(void 0!==f[e]){var b=f[e]-l;n+="&"+m[e]+"="+(0<b?encodeURIComponent(b):0)}else n+="&"+m[e]+"=-1";window[ensightenOptions.ns].timing=n;e=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";n=f.indexOf("/",0);l=f.indexOf("/code/");f=f.substring(n,l)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+e+f)}}});
		
window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(p,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,c){if("[object Array]"===Object.prototype.toString.call(b)){for(var g=0;g<b.length;g++)k.pushTrigger(b[g],c);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof c&&this.queue[b].fn.push(c);return!0},callTrigger:function(b,c,g){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=
b.fireOnFirstSet&&c==u||c!=u&&0!=b.fireOnUpdate))for(c=0;c<b.fn.length;c++)try{b.fn[c].call(this)}catch(n){p[ensightenOptions.ns].reportException(n)}},setPollOptions:function(b,c,g){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=c;this.queue[b].fireOnUpdate=g},callPoll:function(b,c,g,p,r){if("string"==typeof b&&c&&c.length&&!(1>c.length)){for(var n=0;n<c.length;n++)k.setPollOptions(c[n],p,r);k.pushWatch(b,c,g)}},pushWatch:function(b,c,g){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,
eventArr:[],valueFn:g});this.pollQueue[b].eventArr=this.pollQueue[b].eventArr.concat(c);this.pollQueue[b].valueFn=g},globalWatch:function(){setInterval(function(){for(var b in k.pollQueue){var c=k.pollQueue[b],g=c.valueFn(b);if(c.previousVal!==g&&null!==g&&""!==g){for(var n=0;n<c.eventArr.length;n++)k.callTrigger.call(p,c.eventArr[n],c.previousVal,g);k.pollQueue[b].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,c){return k.pushTrigger(b,c)},get:function(b){return k.queue[b]},trigger:function(b,
c){return k.callTrigger.call(c||p,b)},poll:function(b,c,g,n,r){r=r||p[ensightenOptions.ns].data.resolve;return k.callPoll(b,c,r,g,n)}}}(window),function(p,u,k){u[p]=k()}("qwery",window[ensightenOptions.ns],function(){function p(){this.c={}}function u(a){return H.g(a)||H.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,d){for(var e=0,f=a.length;e<f;e++)d(a[e])}function b(a){for(var d=[],e=0,f=a.length;e<f;++e)l(a[e])?d=d.concat(a[e]):d[d.length]=a[e];return d}function c(a){for(var d=0,e=a.length,f=[];d<
e;d++)f[d]=a[d];return f}function g(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function n(a,d,e,f,b,h,l,c,g,k,y){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(a=m.length;a--;)if(!u(m[a].slice(1)).test(this.className))return!1;if(g&&v.pseudos[g]&&!v.pseudos[g](this,y))return!1;if(f&&!l)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==
b)return this;return f&&!x(h,S(this,b)||"",l)?!1:this}function r(a){return J.g(a)||J.s(a,a.replace(T,"\\$1"))}function x(a,d,e){switch(a){case "=":return d==e;case "^=":return d.match(w.g("^="+e)||w.s("^="+e,"^"+r(e),1));case "$=":return d.match(w.g("$="+e)||w.s("$="+e,r(e)+"$",1));case "*=":return d.match(w.g(e)||w.s(e,r(e),1));case "~=":return d.match(w.g("~="+e)||w.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(w.g("|="+e)||w.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function q(a,
d){var e=[],f=[],b,h,l=d,c=C.g(a)||C.s(a,a.split(K)),g=a.match(L);if(!c.length)return e;var m=(c=c.slice(0)).pop();c.length&&(b=c[c.length-1].match(M))&&(l=N(d,b[1]));if(!l)return e;var y=m.match(E);var v=l!==d&&9!==l.nodeType&&g&&/^[+~]$/.test(g[g.length-1])?function(a){for(;l=l.nextSibling;)1==l.nodeType&&(y[1]?y[1]==l.tagName.toLowerCase():1)&&(a[a.length]=l);return a}([]):l.getElementsByTagName(y[1]||"*");b=0;for(m=v.length;b<m;b++)if(h=n.apply(v[b],y))e[e.length]=h;if(!c.length)return e;k(e,
function(a){t(a,c,g)&&(f[f.length]=a)});return f}function t(a,d,e,b){function l(a,b,c){for(;c=U[e[b]](c,a);)if(f(c)&&n.apply(c,d[b].match(E)))if(b){if(h=l(c,b-1,c))return h}else return c}var h;return(h=l(a,d.length-1,a))&&(!b||z(h,b))}function f(a,d){return a&&"object"===typeof a&&(d=a.nodeType)&&(1==d||9==d)}function h(a){var d=[],e;var f=0;a:for(;f<a.length;++f){for(e=0;e<d.length;++e)if(d[e]==a[f])continue a;d[d.length]=a[f]}return d}function l(a){return"object"===typeof a&&isFinite(a.length)}
function N(a,d,e){return 9===a.nodeType?a.getElementById(d):a.ownerDocument&&((e=a.ownerDocument.getElementById(d))&&z(e,a)&&e||!z(a,a.ownerDocument)&&F('[id="'+d+'"]',a)[0])}function v(a,d){var e,h;var g=d?"string"==typeof d?v(d)[0]:!d.nodeType&&l(d)?d[0]:d:m;if(!g||!a)return[];if(a===window||f(a))return!d||a!==window&&f(g)&&z(a,g)?[a]:[];if(a&&l(a))return b(a);if(e=a.match(V)){if(e[1])return(h=N(g,e[1]))?[h]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(a,
g)}function y(a,d){return function(e){var f,b;O.test(e)?9!==a.nodeType&&((b=f=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),d(a.parentNode||a,'[id="'+b+'"]'+e,!0),f||a.removeAttribute("id")):e.length&&d(a,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+~>]|$)\s*/g,A=/[\s>\+~]/,P=/(?![\s\w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,
V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*~]?=)['"]?([ \w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,d){return a&&a.parentNode==d.parentNode&&a.parentNode},"~":function(a){return a&&
a.previousSibling},"+":function(a,d,e,f){return a?(e=g(a))&&(f=g(d))&&e==f&&e:!1}};p.prototype={g:function(a){return this.c[a]||void 0},s:function(a,d,e){d=e?new RegExp(d):d;return this.c[a]=d}};var H=new p,J=new p,w=new p,C=new p,z="compareDocumentPosition"in D?function(a,d){return 16==(d.compareDocumentPosition(a)&16)}:"contains"in D?function(a,d){d=9===d.nodeType||d==window?D:d;return d!==a&&d.contains(a)}:function(a,d){for(;a=a.parentNode;)if(a===d)return 1;return 0},S=function(){var a=m.createElement("p");
return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,e){return"class"===e?a.className:"href"===e||"src"===e?a.getAttribute(e,2):a.getAttribute(e)}:function(a,e){return a.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(a,d){var e=[],f,b;try{if(9===d.nodeType||!O.test(a))return c(d.querySelectorAll(a));k(f=a.split(","),y(d,function(a,d){b=a.querySelectorAll(d);1==b.length?e[e.length]=b.item(0):b.length&&(e=e.concat(c(b)))}));
return 1<f.length&&1<e.length?h(e):e}catch(ba){}return G(a,d)},G=function(a,d){var e=[],f,b;a=a.replace(Y,"$1");if(f=a.match(X)){var l=u(f[2]);f=d.getElementsByTagName(f[1]||"*");var c=0;for(b=f.length;c<b;c++)l.test(f[c].className)&&(e[e.length]=f[c]);return e}k(f=a.split(","),y(d,function(a,f,h){l=q(f,a);c=0;for(b=l.length;c<b;c++)if(9===a.nodeType||h||z(l[c],d))e[e.length]=l[c]}));return 1<f.length&&1<e.length?h(e):e};A=function(a){"undefined"!==typeof a.useNativeQSA&&(F=a.useNativeQSA?Z?aa:G:
G)};A({useNativeQSA:!0});v.configure=A;v.uniq=h;v.is=function(a,d,e){if(f(d))return a==d;if(l(d))return!!~b(d).indexOf(a);for(var c=d.split(","),h;d=c.pop();)if(h=C.g(d)||C.s(d,d.split(K)),d=d.match(L),h=h.slice(0),n.apply(a,h.pop().match(E))&&(!h.length||t(a,h,d,e)))return!0;return!1};v.pseudos={};return v}),function(){function p(f,b,c){n||(n=window[ensightenOptions.ns].qwery);var h=n;if((h=h.call(c,b,c))&&0<h.length){if("_root"==b)f=c;else if(f===c)f=void 0;else{b:{for(var l=h.length,g=0;g<l;g++)if(f===
h[g]){h=!0;break b}h=!1}h||(f.parentNode?(r++,f=p(f.parentNode,b,c)):f=void 0)}return f}return!1}function u(f,b,c,g){q[f.id]||(q[f.id]={});q[f.id][b]||(q[f.id][b]={});q[f.id][b][c]||(q[f.id][b][c]=[]);q[f.id][b][c].push(g)}function k(f,b,c,g){if(g||c)if(g)for(var h=0;h<q[f.id][b][c].length;h++){if(q[f.id][b][c][h]===g){q[f.id][b][c].pop(h,1);break}}else delete q[f.id][b][c];else q[f.id][b]={}}function b(b,c,l){if(q[b][l]){var f=c.target||c.srcElement,h,k,m={},n=k=0;r=0;for(h in q[b][l])q[b][l].hasOwnProperty(h)&&
(k=p(f,h,t[b].element))&&g.matchesEvent(l,t[b].element,k,"_root"==h,c)&&(r++,q[b][l][h].match=k,m[r]=q[b][l][h]);c.stopPropagation=function(){c.cancelBubble=!0};for(k=0;k<=r;k++)if(m[k])for(n=0;n<m[k].length;n++){if(!1===m[k][n].call(m[k].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(c,h,l,n){function f(c){return function(f){b(p,f,c)}}c instanceof Array||(c=[c]);l||"function"!=typeof h||(l=h,h="_root");var p=this.id,m;for(m=0;m<c.length;m++)q[p]&&q[p][c[m]]||g.addEvent(this,c[m],
f(c[m])),n?k(this,c[m],h,l):u(this,c[m],h,l);return this}function g(b,c,l,k){if("string"==typeof b&&"function"==typeof c||"string"==typeof c)g(document).on(b,c,l,k||!1);if(!(this instanceof g)){for(var f in t)if(t[f].element===b)return t[f];x++;t[x]=new g(b,x);t[x]._on=t[x].on;t[x].on=function(b,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);
if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,f)};return t[x]}this.element=b;this.id=c}var n,r=0,x=0,q={},t={};g.prototype.on=function(b,g,l){return c.call(this,b,g,l)};g.prototype.off=function(b,g,l){return c.call(this,b,g,l,!0)};g.cancel=function(b){b.preventDefault();b.stopPropagation()};g.addEvent=function(b,c,g){b.element.addEventListener(c,
g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(p){var u=p.addEvent;p.addEvent=function(k,b,c){if(k.element.addEventListener)return u(k,b,c);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+
b,c)};p.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);
Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;setTimeout(function(){var zaius=window.zaius||(window.zaius=[]),d=window.trb&&trb.data&&trb.data.page&&trb.data.page.metrics,t=d&&d.contentType,id=window.trb&&trb.data&&trb.data.zaiusId;if((t=="story"||t=="column"||t=="post")&&id){zaius.methods=["initialize","onload","event","entity","identify","anonymize","dispatch"];zaius.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);
t.unshift(e);zaius.push(t);return zaius}};for(var i=0;i<zaius.methods.length;i++){var m=zaius.methods[i];zaius[m]=zaius.factory(m)}if(location.href.indexOf("disable-zaius")<0){var e=document.createElement("script");e.async=true;e.src="//d1igp3oop3iho5.cloudfront.net/v2/"+id+"/zaius"+(location.href.indexOf("trb_debug")>0?".js":"-min.js");(document.head||document.body).appendChild(e);zaius.event("pageview");zaius.event("product",{action:"detail",product_id:d.contentId})}}},4E3)},2669094,567505);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var n;(window.trb||(window.trb={})).fbp=function(i,e,o){if(!Bootstrapper.dtv&&location.href.indexOf("disable-fbp")<0){if(!n)n=Date.now();var p="https://www.facebook.com/tr/?id\x3d"+i+"\x26ev\x3d"+e+"\x26ts\x3d"+Date.now()+"\x26it\x3d"+n+"\x26v\x3d2.7.21\x26if\x3d"+(top!==window),u="\x26dl\x3d"+encodeURIComponent(location.href),ul=u.length,r=document.referrer,l=
"\x26rl\x3d"+(r?encodeURIComponent(r):""),pl,k;if(o)for(k in o)if(o.hasOwnProperty(k))p+="\x26cd["+k+"]\x3d"+encodeURIComponent(o[k]);pl=p.length;if(pl+ul<2048){p+=u;pl+=ul}if(pl+l.length<2048)p+=l;(new Image).src=p}}},2505118,[2504899],412366,[393988]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version="2.0";n.queue=[];if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-fbq")<0)setTimeout(function(){t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)},3E3)}(window,document,"script","https://connect.facebook.net/en_US/fbevents.js")},2505131,[2504899],414934,[393988]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var w=window,sn=w.trb&&trb.data&&trb.data.page&&trb.data.page.metrics.siteName,i;if(sn&&!w.kw&&!Bootstrapper.dtv&&location.href.indexOf("disable-keywee")<0){w.kw=1;switch(sn){case "chicagotribune":i=38;break;case "latimes":i=181;break;case "baltimoresun":i=41;break;case "orlandosentinel":i=39;break;case "sun-sentinel":i=40;break;case "sandiegouniontribune":i=335;break;case "courant":i=
42;break;case "mcall":i=43;break;case "dailypress":i=44;break;case "hoylosangeles":i=706;break;case "nydailynews":i=870;break;case "pilotonline":i=745;break}if(i){(w.kwa||(w.kwa=function(){(w.kwa.q=w.kwa.q||[]).push(arguments)}))("initialize",i);setTimeout(function(){var s=document.createElement("script");s.src="//cdn.keywee.co/dist/analytics.min.js";s.async=true;document.head.appendChild(s)},3E3)}}},2949208,450260);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;function bx(){setTimeout(function(){var e=document.createElement("script");e.async=true;e.src="//tag.bounceexchange.com/2452/i.js";document.head.appendChild(e)})}var l;if(!Bootstrapper.dtv&&((l=location.href).indexOf("disable-bouncex")<0&&l.indexOf("adzone\x3d")<0||l.indexOf("enable-bouncex")>=0))trb.runInfuse?trb.runInfuse.push(bx):bx()},2424902,514533);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!Bootstrapper.dtv){var i="202521313812471";fbq("init",i);fbq("track","PageView");var surface;var ua=navigator.userAgent||navigator.vendor||window.opera;if(/[?&]account_linking_token=/.test(location.search)&&/[?&]redirect_uri=/.test(location.search)&&/[?&]surface=/.test(location.search)&&/[?&]article_url=/.test(location.search))surface="IA";else if(/FBAN\//.test(ua)||
/FBIOS\//.test(ua))surface="mWeb";else surface="nonApp";setTimeout(function(){(trb.registration||(trb.registration=[])).push({"event-reg_after_login":function(u){!u&&trb.fbp(i,"LogIntoAccount")},"event-reg_after_register":function(){trb.fbp(i,"CreateAccount")}});var t=trb.data,c=t.page&&t.page.metrics&&t.page.metrics.contentType;c&&/story$|post|column|photog/.test(c)&&(trb.metering||(trb.metering=[])).push({status:function(d){function x(queryString){var params={},value;if(queryString&&typeof queryString==
"string")queryString.replace(/[?#]?([^\[=&]+)(\[\])?(?:(=)([^&]*))?/g,function(a,b,c,d,e){value=e===undefined||e===""?d==="\x3d"?"":true:e;if(c)(params[b]&&params[b].push||(params[b]=[])).push(value);else params[b]=value});return params}var h,r=d.matchedRule,b=r&&r.b||(h=x(location.search)).surface=="meter_limit_reached",l=r&&r.l||(h||(h=x(location.search))).read_count;trb.fbp(i,"ViewContent",{article_content_tier:l?"metered":b?"locked":"free",is_subscriber:d.subscriptionLevels.length>0});b&&trb.fbp(i,
"ViewPaywall",{meter_count:l||0,surface:surface})}})},4E3)}},2807078,[2505118,2505131],514549,[412366,414934]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var t=window.trb&&trb.data&&trb.data.page&&trb.data.page.metrics&&trb.data.page.metrics.contentType,r=document.readyState,b=Bootstrapper;if(t)b.dtv=t.indexOf("video")>-1;if(r=="interactive")b.callOnDOMParsed();else if(r=="complete")b.callOnDOMLoaded()},2504899,393988);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;trb.data.zaiusId="OXN8HLIzKnrwrblKmirZkQ"},2669190,572983);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(location.href.indexOf("disable-bing")<0)setTimeout(function(){if(!Bootstrapper.dtv)(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"11000099"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=
null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq")},3E3)},2431860,537244);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var adWordsTag=document.createElement("script");adWordsTag.async=true;adWordsTag.onload=function(){window.google_trackConversion({google_conversion_id:818526639,google_remarketing_only:true})};adWordsTag.src="https://www.googleadservices.com/pagead/conversion_async.js";document.body.appendChild(adWordsTag)},2471640,526376);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(-1==location.href.indexOf("disable-pulse")){var send=function(c,a,b,h){!pid&&window.localStorage&&(pid=localStorage.getItem("trb.data.lotame.pid"));f||(f=trb.cookie.get("s_fid"));"undefined"==typeof g&&(g=trb.cookie.get("pch")||!1);p||(p=trb.cookie.get("psync_uuid"));a="?pulse1\x3d"+c.eVar35+"\x26pulse3\x3d"+c.server+a;c.eVar34&&(a+="\x26pulse4\x3d"+c.eVar34);c.eVar21&&
(a+="\x26pulse5\x3d"+c.eVar21);referrerVar&&(a+=referrerVar);c.eVar23&&(a+="\x26pulse16\x3d"+encodeURIComponent(c.eVar23));c.eVar20&&(a+="\x26pulse60\x3d"+c.eVar20);f&&(a+="\x26pulse76\x3d"+f);c.prop46&&(a+="\x26pulse92\x3d"+encodeURIComponent(c.prop46));c.prop45&&(a+="\x26pulse124\x3d"+c.prop45);p&&(a+="\x26psync_uuid\x3d"+p);a+="\x26pulse2\x3d"+encodeURIComponent(c.pageURL||location.href)+"\x26pulse125\x3d"+exop+privateModeVar+platformVar+"\x26pei\x3d"+h+"\x26pbrd\x3d"+metrics.pbrd+"\x26pxlid\x3d"+
pageViewId+"\x26sbsup\x3d"+(beaconUnsupported?"f":"t")+"\x26cb\x3d"+cb++;0>a.indexOf("pch\x3d")&&(a+=g?"\x26pch\x3d4\x26prefch\x3d"+g:referrer?"\x26pch\x3d5\x26prefch\x3d5":"\x26pch\x3d9\x26prefch\x3d9");b&&(a+="\x26pcid\x3d"+b);pid&&(a+="\x26pdcoid\x3d"+pid);(new Image).src="https://activate."+prdomain+"/no-content"+a},cb=0,fssorid,metrics=trb.data.metrics,prdomain=metrics.prdomain,hostname=location.hostname,referrer=document.referrer,referrerVar=referrer&&"\x26pulse15\x3d"+encodeURIComponent(referrer),
domainIndex=hostname.lastIndexOf(prdomain),platformVar=-1<domainIndex&&domainIndex+prdomain.length==hostname.length?"\x26pulse93\x3d14":"\x26pulse93\x3d15",pageViewId=metrics.pvid||Date.now()+"_"+Math.floor(1E9*Math.random()),exop=trb.exopid?"true":trb.data.page&&trb.data.page.articleType&&-1<document.cookie.indexOf("xop\x3d0")?"control":"false",privateMode=trb["private"],privateModeVar="\x26pulse138\x3d",beaconUnsupported=!navigator.sendBeacon,pid,g,f,p,first=!0;(function(c){if(privateMode===a){var a,
b=navigator.userAgent,h,k=3;if(window.webkitRequestFileSystem)webkitRequestFileSystem(TEMPORARY,1,function(){privateMode=trb["private"]=!1},function(){privateMode=trb["private"]=!0});else if(-1<b.indexOf("Firefox")&&window.indexedDB)b=indexedDB.open("test"),b.onsuccess=function(){privateMode=trb["private"]=!1},b.onerror=function(){privateMode=trb["private"]=!0};else if(-1<b.indexOf("Edge")||(h=/(?:MSIE|rv:)\s?([\d\.]+)/.exec(b))&&10<=parseInt(h[1],10))privateMode=trb["private"]=!window.indexedDB;
else if(-1<b.indexOf("Safari")&&window.localStorage)try{privateMode=trb["private"]=!openDatabase(null,null,null,null),localStorage.setItem("trbTest",1),localStorage.removeItem("trbTest")}catch(e){privateMode=trb["private"]=!0}}(function d(){privateMode!==a||(privateMode=trb["private"])!==a?c(privateMode):k--?setTimeout(d,50):c(!1)})()})(function(c){privateModeVar+=c?"yes":"no";(trb.dpl||(trb.dpl=[])).push({callback:function(a){var b="";a.prop62&&(b+="\x26pulse6\x3d"+a.prop62);a.prop33&&(b+="\x26pulse7\x3d"+
a.prop33);a.prop34&&(b+="\x26pulse8\x3d"+a.prop34);a.eVar4&&(b+="\x26pulse9\x3d"+a.eVar4);a.eVar5&&(b+="\x26pulse10\x3d"+a.eVar5);a.eVar6&&(b+="\x26pulse11\x3d"+a.eVar6);a.eVar7&&(b+="\x26pulse12\x3d"+a.eVar7);a.eVar8&&(b+="\x26pulse13\x3d"+encodeURIComponent(a.eVar8));a.eVar10&&(b+="\x26pulse14\x3d"+a.eVar10);a.eVar37&&(b+="\x26pulse17\x3d"+a.eVar37);a.eVar38&&(b+="\x26pulse18\x3d"+a.eVar38);a.eVar39&&(b+="\x26pulse19\x3d"+a.eVar39);a.prop21&&(b+="\x26pulse20\x3d"+a.prop21);a.campaign&&(b+="\x26pulse21\x3d"+
encodeURIComponent(a.campaign));a.eVar64&&(b+="\x26pulse22\x3d"+encodeURIComponent(a.eVar64));a.prop44&&(b+="\x26pulse25\x3d"+a.prop44);a.prop64&&(b+="\x26pulse26\x3d"+a.prop64);a.prop59&&(b+="\x26pulse27\x3d"+encodeURIComponent(a.prop59));a.prop63&&(b+="\x26pulse28\x3d"+encodeURIComponent(a.prop63));a.prop3&&(b+="\x26pulse29\x3d"+encodeURIComponent(a.prop3));a.prop22&&(b+="\x26pulse30\x3d"+encodeURIComponent(a.prop22));a.prop23&&(b+="\x26pulse31\x3d"+encodeURIComponent(a.prop23));a.eVar11&&(b+="\x26pulse32\x3d"+
a.eVar11);a.prop32&&(b+="\x26pulse33\x3d"+a.prop32);a.prop36&&(b+="\x26pulse34\x3d"+a.prop36);a.prop37&&(b+="\x26pulse35\x3d"+a.prop37);a.prop51&&(b+="\x26pulse36\x3d"+encodeURIComponent(a.prop51));a.prop58&&(b+="\x26pulse37\x3d"+encodeURIComponent(a.prop58));a.eVar32&&(b+="\x26pulse38\x3d"+a.eVar32);a.events&&(-1<a.events.indexOf("event52")||-1<a.events.indexOf("event67"))&&(b+="\x26pulse41\x3dtrue");a.eVar62&&(b+="\x26pulse47\x3d"+a.eVar62);a.eVar65&&(b+="\x26pulse48\x3d"+a.eVar65);a.eVar66&&(b+=
"\x26pulse49\x3d"+a.eVar66);a.eVar67&&(b+="\x26pulse50\x3d"+a.eVar67);a.eVar55&&(b+="\x26pulse51\x3d"+a.eVar55);a.eVar1&&(b+="\x26pulse56\x3d"+encodeURIComponent(a.eVar1));a.eVar2&&(b+="\x26pulse57\x3d"+encodeURIComponent(a.eVar2));a.eVar14&&(b+="\x26pulse58\x3d"+encodeURIComponent(a.eVar14));a.eVar19&&(b+="\x26pulse59\x3d"+a.eVar19);a.eVar25&&(b+="\x26pulse61\x3d"+encodeURIComponent(a.eVar25));a.eVar27&&(b+="\x26pulse62\x3d"+a.eVar27);a.eVar28&&(b+="\x26pulse63\x3d"+encodeURIComponent(a.eVar28));
a.eVar29&&(b+="\x26pulse64\x3d"+a.eVar29);a.eVar30&&(b+="\x26pulse65\x3d"+encodeURIComponent(a.eVar30));a.eVar47&&(b+="\x26pulse66\x3d"+a.eVar47);a.eVar49&&(b+="\x26pulse67\x3d"+a.eVar49);a.eVar53&&(b+="\x26pulse68\x3d"+a.eVar53);a.eVar54&&(b+="\x26pulse69\x3d"+a.eVar54);a.eVar56&&(b+="\x26pulse70\x3d"+a.eVar56);a.eVar57&&(b+="\x26pulse71\x3d"+a.eVar57);a.eVar58&&(b+="\x26pulse72\x3d"+a.eVar58);a.eVar59&&(b+="\x26pulse73\x3d"+encodeURIComponent(a.eVar59));a.eVar60&&(b+="\x26pulse74\x3d"+a.eVar60);
a.eVar61&&(b+="\x26pulse75\x3d"+a.eVar61);if(a.events)for(var c=0,k=a.events.split(","),e,d,l;c<k.length;c++)if(e=k[c])d=e.indexOf("\x3d"),l=parseInt(-1<d?e.substring(5,d):e.substr(5)),isNaN(l)||(b+="\x26pulse"+(1E3+l)+"\x3d"+(-1<d&&encodeURIComponent(e.substr(d+1))||"true"));a.list1&&(b+="\x26pulse77\x3d"+encodeURIComponent(a.list1));a.pe&&(b+="\x26pulse78\x3d"+a.pe);a.linkName&&(b+="\x26pulse79\x3d"+a.linkName);a.prop57&&(b+="\x26pulse82\x3d"+a.prop57);a.eVar68&&(b+="\x26pulse94\x3d"+a.eVar68);
a.prop48&&(b+="\x26pulse113\x3d"+a.prop48);a.prop55&&(b+="\x26pulse114\x3d"+a.prop55);a.prop75&&(b+="\x26pulse115\x3d"+a.prop75);a.prop68&&(b+="\x26pulse116\x3d"+a.prop68);a.prop52&&(b+="\x26pulse118\x3d"+a.prop52);a.prop69&&(b+="\x26pulse119\x3d"+a.prop69);a.list2&&(b+="\x26pulse120\x3d"+a.list2);a.prop53&&(b+="\x26pulse121\x3d"+a.prop53);a.prop54&&(b+="\x26pulse126\x3d"+a.prop54);first&&(first=!first,setTimeout(function(){var a=trb.dpp,c=trb.dpp={push:function(a){if(a&&"object"==typeof a){var c=
trb.dpl.data&&trb.dpl.data[0];if(c){var d=function(){b=a.pulse6?"":"\x26pulse6\x3d"+(e?"signed-in":"signed-out");if(a.adsystem){var d=trb.data.ads&&trb.data.ads.options,h=2;b+="\x26pch\x3d1\x26ci_paic\x3d1\x26ci_pdic\x3d1\x26pdpm\x3d"+encodeURIComponent(location.href);if("arcdfp"==a.adsystem&&a.event){var m=a.event,k=a.adevent,l=m.slot,n=m.size;a=null;b+="\x26adsystem\x3darcdfp\x26pve\x3d1\x26paduid\x3d"+encodeURIComponent(l.getAdUnitPath()||"")+"\x26pdadvid\x3d"+(m.advertiserId||"")+"\x26pdcrid\x3d"+
(m.creativeId||"")+"\x26pdadid\x3d"+(m.lineItemId||"")+"\x26pdcid\x3d"+(m.campaignId||"")+"\x26emptyadresponse\x3d"+m.isEmpty+"\x26oopad\x3d"+(!!n&&1==n[0]&&1==n[1])+"\x26adsize\x3d"+(n?n[0]+"x"+n[1]:"")+"\x26adtarss\x3d"+(l.getTargeting("ss")||"")+"\x26adtarpos\x3d"+(l.getTargeting("pos")||"");k&&(h="3",b+="\x26adev\x3d"+k)}d&&(b+="\x26adtaradb\x3d"+(d.adb||"")+"\x26adtarexop\x3d"+(d.exop||""))}if(a)for(var q in a)a.hasOwnProperty(q)&&(b+="\x26"+q+"\x3d"+encodeURIComponent(a[q]||""));send(c,b,e,
h||"3")},e=c.prop28||fssorid,h;!e&&((h=trb.registration&&trb.registration.user&&trb.registration.user.isLoggedIn())||!1!==h&&trb.utils&&trb.utils.trySSORuser&&trb.cookie.get("c_mId"))?h?trb.registration.push({user:function(a){a&&(e=fssorid=a.getConsumerId());d()}}):trb.utils.trySSORuser(function(a){a&&a.isLoggedIn()&&(e=fssorid=a.getConsumerId());d()}):d()}}}};a&&"object"==typeof a&&a.forEach&&a.forEach(c.push)}))}})})}},2844337,499052);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;function tb(){setTimeout(function(){window._tfa=window._tfa||[];window._tfa.push({notify:"event",name:"page_view"});!function(t,f,a,x){if(!document.getElementById(x)){t.async=1;t.src=a;t.id=x;f.parentNode.insertBefore(t,f)}}(document.createElement("script"),document.getElementsByTagName("script")[0],"//cdn.taboola.com/libtrc/unip/1157224/tfa.js","tb_tfa_script")})}
if(!Bootstrapper.dtv&&location.href.indexOf("disable-taboola")<0)window.trb&&trb.run?trb.run.push(tb):tb()},2621435,[2504899],563818,[393988]);Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions},2389660,532316);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();